all:
	g++ -std=c++17 -O3 -flto -fvisibility=hidden main.cpp main.h LambdaParser.h LambdaParser.cpp Type.cpp Type.h Substitution.h Substitution.cpp Equation.cpp Equation.h -o ParenthesisInLambda
run:
	./ParenthesisInLambda
